//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIKI.GoRoomy.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HotelReservationLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HotelReservationLabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IIKI.GoRoomy.Localization.Resources.HotelReservationLabels", typeof(HotelReservationLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation.
        /// </summary>
        public static string AddEditTitle {
            get {
                return ResourceManager.GetString("AddEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Date.
        /// </summary>
        public static string BookingDateTime {
            get {
                return ResourceManager.GetString("BookingDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Date is Required.
        /// </summary>
        public static string BookingDateTimeRequired {
            get {
                return ResourceManager.GetString("BookingDateTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-In Date Time.
        /// </summary>
        public static string CheckInDateTime {
            get {
                return ResourceManager.GetString("CheckInDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-In Date Time is Required.
        /// </summary>
        public static string CheckInDateTimeRequired {
            get {
                return ResourceManager.GetString("CheckInDateTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-Out Date Time.
        /// </summary>
        public static string CheckOutDateTime {
            get {
                return ResourceManager.GetString("CheckOutDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-Out Date Time is Required.
        /// </summary>
        public static string CheckOutDateTimeRequired {
            get {
                return ResourceManager.GetString("CheckOutDateTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Comments.
        /// </summary>
        public static string CustomerComments {
            get {
                return ResourceManager.GetString("CustomerComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Comments is Required.
        /// </summary>
        public static string CustomerCommentsRequired {
            get {
                return ResourceManager.GetString("CustomerCommentsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Contact Name.
        /// </summary>
        public static string EmergencyContactName {
            get {
                return ResourceManager.GetString("EmergencyContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Contact Name is Required.
        /// </summary>
        public static string EmergencyContactNameRequired {
            get {
                return ResourceManager.GetString("EmergencyContactNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Contact Number.
        /// </summary>
        public static string EmergencyContactNumber {
            get {
                return ResourceManager.GetString("EmergencyContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Contact Number is Required.
        /// </summary>
        public static string EmergencyContactNumberRequired {
            get {
                return ResourceManager.GetString("EmergencyContactNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Comments.
        /// </summary>
        public static string HotelComments {
            get {
                return ResourceManager.GetString("HotelComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Comments is Required.
        /// </summary>
        public static string HotelCommentsRequired {
            get {
                return ResourceManager.GetString("HotelCommentsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        public static string PaymentMethodId {
            get {
                return ResourceManager.GetString("PaymentMethodId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method is Required.
        /// </summary>
        public static string PaymentMethodIdRequired {
            get {
                return ResourceManager.GetString("PaymentMethodIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion Comments.
        /// </summary>
        public static string PromotionComments {
            get {
                return ResourceManager.GetString("PromotionComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion Comments is Required.
        /// </summary>
        public static string PromotionCommentsRequired {
            get {
                return ResourceManager.GetString("PromotionCommentsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion.
        /// </summary>
        public static string PromotionId {
            get {
                return ResourceManager.GetString("PromotionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion is Required.
        /// </summary>
        public static string PromotionIdRequired {
            get {
                return ResourceManager.GetString("PromotionIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation.
        /// </summary>
        public static string ReservationId {
            get {
                return ResourceManager.GetString("ReservationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation is Required.
        /// </summary>
        public static string ReservationIdRequired {
            get {
                return ResourceManager.GetString("ReservationIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation Made By.
        /// </summary>
        public static string ReservationMadeByStatusId {
            get {
                return ResourceManager.GetString("ReservationMadeByStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation Made By is Required.
        /// </summary>
        public static string ReservationMadeByStatusIdRequired {
            get {
                return ResourceManager.GetString("ReservationMadeByStatusIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation Status.
        /// </summary>
        public static string ReservationStatusId {
            get {
                return ResourceManager.GetString("ReservationStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation Status is Required.
        /// </summary>
        public static string ReservationStatusIdRequired {
            get {
                return ResourceManager.GetString("ReservationStatusIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservations.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        public static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount Paid.
        /// </summary>
        public static string TotalAmountPaid {
            get {
                return ResourceManager.GetString("TotalAmountPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount Paid is Required.
        /// </summary>
        public static string TotalAmountPaidRequired {
            get {
                return ResourceManager.GetString("TotalAmountPaidRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount is Required.
        /// </summary>
        public static string TotalAmountRequired {
            get {
                return ResourceManager.GetString("TotalAmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Discount.
        /// </summary>
        public static string TotalDiscount {
            get {
                return ResourceManager.GetString("TotalDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Discount is Required.
        /// </summary>
        public static string TotalDiscountRequired {
            get {
                return ResourceManager.GetString("TotalDiscountRequired", resourceCulture);
            }
        }
    }
}
