//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIKI.GoRoomy.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HotelSlotLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HotelSlotLabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IIKI.GoRoomy.Localization.Resources.HotelSlotLabels", typeof(HotelSlotLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot.
        /// </summary>
        public static string AddEditTitle {
            get {
                return ResourceManager.GetString("AddEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Slots.
        /// </summary>
        public static string HotelRoomSlots {
            get {
                return ResourceManager.GetString("HotelRoomSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Slots is Required.
        /// </summary>
        public static string HotelRoomSlotsRequired {
            get {
                return ResourceManager.GetString("HotelRoomSlotsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot.
        /// </summary>
        public static string HotelSlotId {
            get {
                return ResourceManager.GetString("HotelSlotId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot is Required.
        /// </summary>
        public static string HotelSlotIdRequired {
            get {
                return ResourceManager.GetString("HotelSlotIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate is Required.
        /// </summary>
        public static string RateRequired {
            get {
                return ResourceManager.GetString("RateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot Description.
        /// </summary>
        public static string SlotDescription {
            get {
                return ResourceManager.GetString("SlotDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot Hours.
        /// </summary>
        public static string SlotHours {
            get {
                return ResourceManager.GetString("SlotHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot Hours is Required.
        /// </summary>
        public static string SlotHoursRequired {
            get {
                return ResourceManager.GetString("SlotHoursRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Rate.
        /// </summary>
        public static string SlotMaxRate {
            get {
                return ResourceManager.GetString("SlotMaxRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Rate is Required.
        /// </summary>
        public static string SlotMaxRateRequired {
            get {
                return ResourceManager.GetString("SlotMaxRateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Rate.
        /// </summary>
        public static string SlotMinRate {
            get {
                return ResourceManager.GetString("SlotMinRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Rate is Required.
        /// </summary>
        public static string SlotMinRateRequired {
            get {
                return ResourceManager.GetString("SlotMinRateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slots.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
