using IIKI.BaseApp.Utils;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System;

namespace IIKI.GoRoomy.Business.Objects
{
    public class HotelAddress : BaseApp.Business.Objects.BaseEntity
    {
        [DataField(Type = DbType.Int64)]
        [Display(Name = "HotelId", ResourceType = typeof(IIKI.GoRoomy.Localization.Resources.HotelLabels))]
        //[Required(ErrorMessageResourceName = "HotelIdRequired", ErrorMessageResourceType = typeof(IIKI.BaseApp.Localization.Resources.HotelLabels))]
        public long HotelId { get; set; }

        [DataField(Type = DbType.Int64)]
        [Display(Name = "AddressId", ResourceType = typeof(IIKI.BaseApp.Localization.Resources.AddressLabels))]
        //[Required(ErrorMessageResourceName = "AddressIdRequired", ErrorMessageResourceType = typeof(IIKI.BaseApp.Localization.Resources.AddressLabels))]
        public long AddressId { get; set; }

        [AutoGeneratedField(Type = DbType.String)]
        [Display(Name = "RecordGUID", ResourceType = typeof(IIKI.BaseApp.Localization.Resources.CommonLabels))]
        public Guid RecordGUID { get; set; }

        [DataField(Type = DbType.Boolean)]
        [Display(Name = "IsDefault", ResourceType = typeof(IIKI.BaseApp.Localization.Resources.CommonLabels))]
        //[Required(ErrorMessageResourceName = "IsDefaultRequired", ErrorMessageResourceType = typeof(IIKI.BaseApp.Localization.Resources.HotelAddressLabels))]
        public bool IsDefault { get; set; }

        [DataField(Type = DbType.Int32, IsShowOnForm = false)]
        [Display(Name = "RecordStatus", ResourceType = typeof(IIKI.BaseApp.Localization.Resources.CommonLabels))]
        public byte? RecordStatus { get; set; }

        [DataField(Type = DbType.DateTimeOffset, IsShowOnForm = false, IsShowInGrid = false)]
        [Display(Name = "CreatedDate", ResourceType = typeof(IIKI.BaseApp.Localization.Resources.CommonLabels))]
        public DateTimeOffset? CreatedDate { get; set; }

        [DataField(Type = DbType.String, IsShowOnForm = false, IsShowInGrid = false)]
        [Display(Name = "CreatedBy", ResourceType = typeof(IIKI.BaseApp.Localization.Resources.CommonLabels))]
        public string CreatedBy { get; set; }

        [DataField(Type = DbType.DateTimeOffset, IsShowOnForm = false, IsShowInGrid = false)]
        [Display(Name = "UpdatedDate", ResourceType = typeof(IIKI.BaseApp.Localization.Resources.CommonLabels))]
        public DateTimeOffset? UpdatedDate { get; set; }

        [DataField(Type = DbType.String, IsShowOnForm = false, IsShowInGrid = false)]
        [Display(Name = "updatedBy", ResourceType = typeof(IIKI.BaseApp.Localization.Resources.CommonLabels))]
        public string updatedBy { get; set; }

    }
}