using IIKI.BaseApp.Localization.Resources;
using IIKI.BaseApp.Utils;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System;

namespace IIKI.GoRoomy.Business.Objects
{
    [DataTable("dbo.tblHotelRoomTypes")]
    [StoreProcedure("dbo.usp_GetHotelRoomTypes")]
    public class HotelRoomType : BaseApp.Business.Objects.BaseEntity
    {
        [AutoGeneratedField(Type = DbType.String)]
        [Display(Name = "RecordCode", ResourceType = typeof(IIKI.BaseApp.Localization.Resources.CommonLabels))]
        public string RoomTypeCode { get; set; }

        [DropDownText]
        [DataField(Type = DbType.String)]
        [Display(Name = "RecordName", ResourceType = typeof(IIKI.BaseApp.Localization.Resources.CommonLabels))]
        //[Required(ErrorMessageResourceName = "RecordNameRequired", ErrorMessageResourceType = typeof(CommonLabels))]
        [StringLength(512, ErrorMessageResourceName = "StringMinMaxLength", ErrorMessageResourceType = typeof(CommonLabels), MinimumLength = 0)]
        public string RoomTypeName { get; set; }

        [DataField(Type = DbType.String)]
        [Display(Name = "RecordDescription", ResourceType = typeof(IIKI.BaseApp.Localization.Resources.CommonLabels))]
        //[Required(ErrorMessageResourceName = "RecordDescriptionRequired", ErrorMessageResourceType = typeof(CommonLabels))]
        [StringLength(512, ErrorMessageResourceName = "StringMinMaxLength", ErrorMessageResourceType = typeof(CommonLabels), MinimumLength = 0)]
        public string RoomTypeDescription { get; set; }

        [DataField(Type = DbType.Int64)]
        [Display(Name = "HotelId", ResourceType = typeof(IIKI.GoRoomy.Localization.Resources.HotelLabels))]
        //[Required(ErrorMessageResourceName = "HotelIdRequired", ErrorMessageResourceType = typeof(IIKI.BaseApp.Localization.Resources.HotelLabels))]
        public long? HotelId { get; set; }

        [DataField(Type = DbType.Int32, IsShowOnForm = false)]
        [Display(Name = "RecordStatus", ResourceType = typeof(IIKI.BaseApp.Localization.Resources.CommonLabels))]
        public int? RecordStatus { get; set; }

        [DataField(Type = DbType.String, IsShowOnForm = false, IsShowInGrid = false)]
        [Display(Name = "CreatedBy", ResourceType = typeof(IIKI.BaseApp.Localization.Resources.CommonLabels))]
        public string CreatedBy { get; set; }

        [DataField(Type = DbType.DateTimeOffset, IsShowOnForm = false, IsShowInGrid = false)]
        [Display(Name = "CreatedDate", ResourceType = typeof(IIKI.BaseApp.Localization.Resources.CommonLabels))]
        public DateTimeOffset? CreatedDate { get; set; }

        [DataField(Type = DbType.String, IsShowOnForm = false, IsShowInGrid = false)]
        [Display(Name = "UpdatedBy", ResourceType = typeof(IIKI.BaseApp.Localization.Resources.CommonLabels))]
        public string UpdatedBy { get; set; }

        [DataField(Type = DbType.DateTimeOffset, IsShowOnForm = false, IsShowInGrid = false)]
        [Display(Name = "UpdatedDate", ResourceType = typeof(IIKI.BaseApp.Localization.Resources.CommonLabels))]
        public DateTimeOffset? UpdatedDate { get; set; }

    }
}