using IIKI.BaseApp.Utils;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System;
using System.Collections.Generic;
using IIKI.BaseApp.Common;
using System.ComponentModel.DataAnnotations.Schema;

namespace IIKI.GoRoomy.Business.Objects
{
    [DataTable("dbo.tblHotelRooms")]
    [StoreProcedure("dbo.usp_GetHotelRooms")]
    public class HotelRoom : BaseApp.Business.Objects.BaseEntity
    {
        public HotelRoom()
        {
            RoomImages = new List<BaseApp.Business.Objects.EntityDocument>();
            HotelRoomSlotsList = new List<GoRoomy.Business.Objects.HotelRoomSlot>();
            //Hotel = new Hotel();
            RoomServices = new HotelRoomService();
        }

        [DataField(IsShowInGrid = false, IsShowOnForm = false, Type = DbType.Int64, FieldOrderOnForm = 0.1f, RenderMode = BaseApp.Common.InputRenderModes.Hidden)]
        [Display(Name = "HotelId", ResourceType = typeof(IIKI.GoRoomy.Localization.Resources.HotelLabels))]
        [Required(ErrorMessageResourceName = "HotelIdRequired", ErrorMessageResourceType = typeof(IIKI.GoRoomy.Localization.Resources.HotelLabels))]
        public long HotelId { get; set; }

        [DataField(IsShowInGrid = false, Type = DbType.Int64, FieldOrderOnForm = 1.2f, RenderMode = BaseApp.Common.InputRenderModes.Dropdown)]
        [Display(Name = "HotelRoomTypeId", ResourceType = typeof(IIKI.GoRoomy.Localization.Resources.HotelRoomTypeLabels))]
        [Required(ErrorMessageResourceName = "HotelRoomTypeIdRequired", ErrorMessageResourceType = typeof(IIKI.GoRoomy.Localization.Resources.HotelRoomTypeLabels))]
        public long? RoomTypeId { get; set; }

        [DropDownText]
        [AutoGeneratedField(IsShowInGrid = false, FieldOrderOnForm = 1.1f, Type = DbType.String)]
        [Display(Name = "RecordCode", ResourceType = typeof(IIKI.BaseApp.Localization.Resources.CommonLabels))]
        public string RoomCode { get; set; }

        [DataField(Type = DbType.String)]
        [Display(Name = "RoomNumber", ResourceType = typeof(IIKI.GoRoomy.Localization.Resources.HotelRoomLabels))]
        //[Required(ErrorMessageResourceName = "RoomNumberRequired", ErrorMessageResourceType = typeof(IIKI.BaseApp.Localization.Resources.HotelRoomLabels))]
        [StringLength(20, ErrorMessageResourceName = "StringMinMaxLength", ErrorMessageResourceType = typeof(IIKI.BaseApp.Localization.Resources.CommonLabels), MinimumLength = 0)]
        public string RoomNumber { get; set; }

        [DataField(Type = DbType.String)]
        [Display(Name = "RecordName", ResourceType = typeof(IIKI.BaseApp.Localization.Resources.CommonLabels))]
        //[Required(ErrorMessageResourceName = "RecordNameRequired", ErrorMessageResourceType = typeof(CommonLabels))]
        [StringLength(512, ErrorMessageResourceName = "StringMinMaxLength", ErrorMessageResourceType = typeof(IIKI.BaseApp.Localization.Resources.CommonLabels), MinimumLength = 0)]
        public string RoomName { get; set; }

        [DataField(IsShowInGrid = false, Type = DbType.Decimal)]
        [Display(Name = "MinRoomPrice", Prompt = "MinRoomPrice"/*, Order = 0, GroupName = "", ShortName = "", Description = "", AutoGenerateField = false, AutoGenerateFilter = false*/)]

        [Required(ErrorMessage = "MinRoomPrice is Required"/*, AllowEmptyStrings = false*/)]
        public decimal? MinRoomPrice { get; set; }

        [DataField(IsShowInGrid = false, Type = DbType.Decimal)]
        [Display(Name = "MaxRoomPrice", Prompt = "MaxRoomPrice"/*, Order = 0, GroupName = "", ShortName = "", Description = "", AutoGenerateField = false, AutoGenerateFilter = false*/)]

        [Required(ErrorMessage = "MaxRoomPrice is Required"/*, AllowEmptyStrings = false*/)]
        public decimal? MaxRoomPrice { get; set; }

        [DataField(Type = DbType.Decimal)]
        [Display(Name = "RoomPrice", Prompt = "RoomPrice"/*, Order = 0, GroupName = "", ShortName = "", Description = "", AutoGenerateField = false, AutoGenerateFilter = false*/)]

        [Required(ErrorMessage = "RoomPrice is Required"/*, AllowEmptyStrings = false*/)]
        public decimal? RoomPrice { get; set; }

        //[DataField(IsShowInGrid = false, Type = DbType.Decimal)]
        //[Display(Name = "FirstSlotTime", Prompt = "FirstSlotTime"/*, Order = 0, GroupName = "", ShortName = "", Description = "", AutoGenerateField = false, AutoGenerateFilter = false*/)]

        //[Required(ErrorMessage = "FirstSlotTime is Required"/*, AllowEmptyStrings = false*/)]
        //public decimal? FirstSlotTime { get; set; }

        //[DataField(IsShowInGrid = false, Type = DbType.Decimal)]
        //[Display(Name = "FirstSlotRate", Prompt = "FirstSlotRate"/*, Order = 0, GroupName = "", ShortName = "", Description = "", AutoGenerateField = false, AutoGenerateFilter = false*/)]

        //[Required(ErrorMessage = "FirstSlotRate is Required"/*, AllowEmptyStrings = false*/)]
        //public decimal? FirstSlotRate { get; set; }

        //[DataField(IsShowInGrid = false, Type = DbType.Decimal)]
        //[Display(Name = "SecondSlotTime", Prompt = "SecondSlotTime"/*, Order = 0, GroupName = "", ShortName = "", Description = "", AutoGenerateField = false, AutoGenerateFilter = false*/)]

        //[Required(ErrorMessage = "SecondSlotTime is Required"/*, AllowEmptyStrings = false*/)]
        //public decimal? SecondSlotTime { get; set; }

        //[DataField(IsShowInGrid = false, Type = DbType.Decimal)]
        //[Display(Name = "SecondSlotRate", Prompt = "SecondSlotRate"/*, Order = 0, GroupName = "", ShortName = "", Description = "", AutoGenerateField = false, AutoGenerateFilter = false*/)]

        //[Required(ErrorMessage = "SecondSlotRate is Required"/*, AllowEmptyStrings = false*/)]
        //public decimal? SecondSlotRate { get; set; }

        //[DataField(IsShowInGrid = false, Type = DbType.Decimal)]
        //[Display(Name = "ThirdSlotTime", Prompt = "ThirdSlotTime"/*, Order = 0, GroupName = "", ShortName = "", Description = "", AutoGenerateField = false, AutoGenerateFilter = false*/)]

        //[Required(ErrorMessage = "ThirdSlotTime is Required"/*, AllowEmptyStrings = false*/)]
        //public decimal? ThirdSlotTime { get; set; }

        //[DataField(IsShowInGrid = false, Type = DbType.Decimal)]
        //[Display(Name = "ThirdSlotRate", Prompt = "ThirdSlotRate"/*, Order = 0, GroupName = "", ShortName = "", Description = "", AutoGenerateField = false, AutoGenerateFilter = false*/)]

        //[Required(ErrorMessage = "ThirdSlotRate is Required"/*, AllowEmptyStrings = false*/)]
        //public decimal? ThirdSlotRate { get; set; }

        //[DataField(IsShowInGrid = false, Type = DbType.Decimal)]
        //[Display(Name = "ForthSlotTime", Prompt = "ForthSlotTime"/*, Order = 0, GroupName = "", ShortName = "", Description = "", AutoGenerateField = false, AutoGenerateFilter = false*/)]

        //[Required(ErrorMessage = "ForthSlotTime is Required"/*, AllowEmptyStrings = false*/)]
        //public decimal? ForthSlotTime { get; set; }

        //[DataField(IsShowInGrid = false, Type = DbType.Decimal)]
        //[Display(Name = "ForthSlotRate", Prompt = "ForthSlotRate"/*, Order = 0, GroupName = "", ShortName = "", Description = "", AutoGenerateField = false, AutoGenerateFilter = false*/)]

        //[Required(ErrorMessage = "ForthSlotRate is Required"/*, AllowEmptyStrings = false*/)]
        //public decimal? ForthSlotRate { get; set; }

        [DataField(IsShowInGrid = false, Type = DbType.String, BootstrapLayoutCol = 12, FieldOrderOnForm = 50000, RenderMode = InputRenderModes.Textarea)]
        [Display(Name = "RecordDescription", ResourceType = typeof(IIKI.BaseApp.Localization.Resources.CommonLabels))]
        //[Required(ErrorMessageResourceName = "RecordDescriptionRequired", ErrorMessageResourceType = typeof(CommonLabels))]
        [StringLength(512, ErrorMessageResourceName = "StringMinMaxLength", ErrorMessageResourceType = typeof(IIKI.BaseApp.Localization.Resources.CommonLabels), MinimumLength = 0)]
        public string RoomDescription { get; set; }

        [DataField(Type = DbType.Int32, IsShowOnForm = false)]
        [Display(Name = "RecordStatus", ResourceType = typeof(IIKI.BaseApp.Localization.Resources.CommonLabels))]
        public int? RecordStatus { get; set; }

        [DataField(IsShowInGrid = false, Type = DbType.String, IsShowOnForm = false)]
        [Display(Name = "CreatedBy", ResourceType = typeof(IIKI.BaseApp.Localization.Resources.CommonLabels))]
        public string CreatedBy { get; set; }

        [DataField(IsShowInGrid = false, Type = DbType.DateTimeOffset, IsShowOnForm = false)]
        [Display(Name = "CreatedDate", ResourceType = typeof(IIKI.BaseApp.Localization.Resources.CommonLabels))]
        public DateTimeOffset? CreatedDate { get; set; }

        [DataField(IsShowInGrid = false, Type = DbType.String, IsShowOnForm = false)]
        [Display(Name = "UpdatedBy", ResourceType = typeof(IIKI.BaseApp.Localization.Resources.CommonLabels))]
        public string UpdatedBy { get; set; }

        [DataField(IsShowInGrid = false, Type = DbType.DateTimeOffset, IsShowOnForm = false)]
        [Display(Name = "UpdatedDate", ResourceType = typeof(IIKI.BaseApp.Localization.Resources.CommonLabels))]
        public DateTimeOffset? UpdatedDate { get; set; }

        ////
        ///Read Only properties
        ///
        [Display(Name = "TotalCount", ResourceType = typeof(IIKI.BaseApp.Localization.Resources.CommonLabels))]
        [ReadOnlyField(Type = DbType.Int32)]
        [System.ComponentModel.DataAnnotations.Schema.NotMapped]
        public int TotalCount { get; set; }

        [Display(Name = "HotelName", ResourceType = typeof(IIKI.GoRoomy.Localization.Resources.HotelLabels))]
        [ReadOnlyField(Type = DbType.String, FieldOrderOnForm = 1, IsShowOnForm = true, RenderMode = InputRenderModes.Readonly)]
        [System.ComponentModel.DataAnnotations.Schema.NotMapped]
        public string HotelName { get; set; }

        //[Display(Name = "HotelFullAddress", ResourceType = typeof(IIKI.GoRoomy.Localization.Resources.HotelLabels))]
        //[ReadOnlyField(IsShowOnForm = false, Type = DbType.String)]
        //[System.ComponentModel.DataAnnotations.Schema.NotMapped]
        //public string HotelFullAddress { get; set; }

        [Display(Name = "HotelRoomSlots", ResourceType = typeof(IIKI.GoRoomy.Localization.Resources.HotelSlotLabels))]
        [NonDBField(IsShowOnForm = false, IsShowInGrid = false, Type = DbType.String)]
        [NotMapped]
        public string RoomSlotsIdsCSV { get; set; }

        [Display(Name = "HotelRoomSlots", ResourceType = typeof(IIKI.GoRoomy.Localization.Resources.HotelSlotLabels))]
        [NotMapped]
        [NonDBField(IsShowOnForm = true, RenderMode = InputRenderModes.InputMultiselect, Type = DbType.String)]
        public IEnumerable<int> RoomSlotsIdsList { get; set; }




        [System.ComponentModel.DataAnnotations.Schema.NotMapped]
        public List<BaseApp.Business.Objects.EntityDocument> RoomImages { get; set; }

        //[System.ComponentModel.DataAnnotations.Schema.NotMapped]
        //public IIKI.GoRoomy.Business.Objects.Hotel Hotel { get; set; }

        [System.ComponentModel.DataAnnotations.Schema.NotMapped]
        public IIKI.GoRoomy.Business.Objects.HotelRoomService RoomServices { get; set; }

        [System.ComponentModel.DataAnnotations.Schema.NotMapped]
        public List<GoRoomy.Business.Objects.HotelRoomSlot> HotelRoomSlotsList { get; set; }
    }
}